/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in the repo so
// TypeScript tooling has the expected ambient types from the first install.
